version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: true
permissions:
  - object: /var/www/html/
    owner: ec2-user
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
    - location: scripts/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300

